### ISSUE TITLE
Recommend 317 test server?

### ISSUE THREAD

**Issue by ghost** [HelloKitty/RS317.Sharp#2]
I tried on luna server and get:
```
08 Jul 2019 14:01:57 io.luna.net.LunaUpstreamHandler [nioEventLoopGroup-2-2]
WARN: Disconnecting LoginClient{ip=127.0.0.1}, upstream exception thrown.
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: opcode != 14
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: opcode != 14
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507) ~[guava-27.0.1-jre.jar:?]
	at io.luna.net.codec.login.LoginDecoder.decodeHandshake(LoginDecoder.java:130) ~[classes/:?]
	at io.luna.net.codec.login.LoginDecoder.decodeMsg(LoginDecoder.java:101) ~[classes/:?]
	at io.luna.net.codec.login.LoginDecoder.decodeMsg(LoginDecoder.java:28) ~[classes/:?]
	at io.luna.net.codec.ProgressiveMessageDecoder.decode(ProgressiveMessageDecoder.java:42) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.32.Final.jar:4.1.32.Final]
	... 20 more
08 Jul 2019 14:01:57 io.luna.net.LunaUpstreamHandler [nioEventLoopGroup-2-2]
```

**Comment by ghost** [comment]
Looking at the client error, it says it is cache, related, I will try to fix that and then report back.

RS2 user client - release #317
```
Error: Failed to load cache. Reason: Failed to generate and write uid. Reason: Could not find a part of the path 'G:\git\RS317.Sharp\src\Rs317.Client.WF\bin\Debug\net472\cache\uid.dat'.
 StackTrack:    at Rs317.Sharp.signlink.getuid(String s) in G:\git\RS317.Sharp\src\Rs317.Library\sign\signlink.cs:line 76
   at Rs317.Sharp.signlink.run() in G:\git\RS317.Sharp\src\Rs317.Library\sign\signlink.cs:line 260
Error: Error loading. During: Requesting title screen State: 25% Reason: Index was outside the bounds of the array.

 Stack:    at Rs317.Sharp.Buffer.getUnsignedLEShort() in G:\git\RS317.Sharp\src\Rs317.Library\Buffer.cs:line 221
   at Rs317.Sharp.Archive..ctor(Byte[] data) in G:\git\RS317.Sharp\src\Rs317.Library\Archive.cs:line 40
   at Rs317.Sharp.Client.requestArchive(Int32 i, String s, String s1, Int32 j, Int32 k) in G:\git\RS317.Sharp\src\Rs317.Client.WF\Client.cs:line 11005
   at Rs317.Sharp.Client.startUp() in G:\git\RS317.Sharp\src\Rs317.Client.WF\Client.cs:line 11533
Error screen!
```

Error screen!
(repeats)

**Comment by ghost** [comment]
tried 4x diff caches that say work with 317:
RS2 user client - release #317
Error: Error loading. During: Requesting config State: 30% Reason: Index was outside the bounds of the array.

> Which cache do you test with?

**Comment by HelloKitty** [comment]
Hmmm, put the cache in a folder called Cache. If you have a 317 cache put it there. Maybe that is non-standard but that is the path I made the client expect.

I can add this to the documentation at some point.

Sorry for responding so late. I didn't expect anyone to post here, let alone even use the client. I am glad someone is interested though! Let me know how the performance is on your machine.

**Comment by HelloKitty** [comment]
The error your server got is likely from when the client saw it had no cache and attempted to download it.

**Comment by ghost** [comment]
I was able to find a better cache that allowed the login screen to load in winforms (I think that is how you have it setup)
I can type in the login/pass and handshake a few 317 servers I am using for testing. astraeus-server is the main one and then luna, the issue now is RSA. I tried a quick look at the code and the only part with BigInteger I could find that looked like where the mitm rsa key goes -> seemed to generate a random key instead of one I provide. do you know what I talking about or do I need to find the code and post it? (no problem for me to do that, just not handy as I moved on to next issue i was solving and will take a bit to find again)

**Comment by HelloKitty** [comment]
I could add the RSA, I had it at one point. The issue was making it toggable. The servers I used for testing didn't use RSA. Since most servers don't use it I didn't add it. I was sleeping so I couldn't respond.

Maybe I can add a conditional compilation for it. But those are a pain in C# vs something like C++.

Any other issues? I'll be happy to look into fixing any bugs in the client, I already had to fix afew from bugs from 317refactor lol.

**Comment by HelloKitty** [comment]
As for the server I used for testing, it is some barley working server from 2010 called Shard Revolution. Just good enough for logging in really.

**Comment by ghost** [comment]
Great, info. It is late here, so I will check that out and try to get at least where you left off working tomorrow. This is the best c# working example I have found that doesn't depend on XNA or Unity so I plan to play for a while with it.

**Comment by HelloKitty** [comment]
Well, there was Rs2Sharp before this, did it lack something? I'm glad someone in the community is interested in the project. I am rather mee to RSPS stuff so this is my first project, I wasn't sure people would have a use for a C# version of a historically Java game.

There is kinda a WIP OpenGL client in the repo now too, other than winforms.

**Comment by HelloKitty** [comment]
You may be happy to know that I should have improved the performance of the Winforms client with: 3f0ba370a95a15e6267959f23e4649fbe15fab83

I also did something EVEN FURTHER with the OpenGL client, it is even more efficient in its process of pushing pixels to the renderer: 61284191762d7ab4e99f2a918df5243689bb6c52

**Comment by ghost** [comment]
I was able to solve this, thanks to your hint. I haven't pulled the latest, looking forward to it.

To answer your question about Rs2Sharp, I never stumbled on that one. I think I mainly just liked yours worked out of the box or after 2x-3x tries or something. I certainly will see if I can find the Rs2Sharp repo. I do like where yours is going, I think that was the other thing, I wanted something to play with that someone else was actively working on. :-)

I think if we want others to join us (if you plan to keep plugging away here on this repo) we should help them source the test server, or stand one up. At present, I can offer further assistance if someone else needs it by replying here for more info.

**Comment by HelloKitty** [comment]
@communityus Glad you were able to solve it.

I wouldn't recommend RS2Sharp anymore. There is no git repository for it, just a source download. RS2Sharp also uses Winforms/GDI rendering, but it is based on a non-renamed client. On top of that the performance is significantly worse for rendering in Rs2Sharp. But I was just curious why you hadn't used that before, the Unity3D projects tend to use it. Like OSHD.

Yea, I think it would be a good idea to have a server. I've actually begun implementing the the packet DTOs for the upcoming C# server. It won't be 100% RS317 protocol compliant, since I don't care to bother with the burden of that. But it will work for this C# client, and the C# client will always remain 317 compliant, but may have new added implementations that aren't.

**Comment by ghost** [comment]
Great. I'm down to help with that server too.

**Comment by ghost** [comment]
I forgot another reason your repo was a choice for us. With Winforms support coming to net core 3.0, it means easily portable client.

**Comment by HelloKitty** [comment]
@communityus Winforms .NET Core 3.0 support is a great thing, it's going to significantly increase the performance of Winforms.

However, it won't actually make Winforms crossplatform. It's just going to be able to run on .NET Core on Windows, the Winforms libraries are not crossplatform.

If you want a .NET/C# potentially crossplatform client, the OpenTK/OpenGL implementation I created the other day is going to. It uses OpenGL to render the screen and OpenTK is almost, or soon to be, crossplatform.

**Comment by ghost** [comment]
This is a place to source the No-Doze server.
https://www.rune-server.ee/runescape-development/rs2-server/downloads/683176-various-old-rs2-sources.html

Always scan for virus etc. like from places like VirusTotal.com

**Comment by ghost** [comment]
Reopening until we get a server. :-)

**Comment by ghost** [comment]
Closing this out.
https://github.com/HelloKitty/RS317.Sharp/issues/6
